import '@/styles/globals.css';
import Head from 'next/head';
import type { AppProps } from 'next/app';

export default function App({ Component, pageProps }: AppProps) {
  return <div>
    <Head>
      <title>Create Next</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link key={1} rel="icon" href="/favicon2.ico" />
    </Head>
    <Component {...pageProps} />
  </div>;
}
